### ISSUE TITLE
Icone for PolishNewsFeed

### ISSUE THREAD

**Issue by hafizahmmed** [eovka/PolishNewsFeed#1]
Hello,
Good Day, i make a logo icon for your project.Because there is no logo in your project. If you want to use this icon in your project, then comment below, I will give you the source file. And if you want a change, then tell me I will change.

![polishnewsfeed-01](https://user-images.githubusercontent.com/38810169/40271493-daa50af2-5bbf-11e8-8502-a846f9cf8d9b.jpg)

**Comment by udrabinska** [comment]
Hello,
thanks for the icon, I already created one by myself. Probably it isn't as good as yours, but at least it is. 
Have a nice day! :)
